[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

monitor_filters = esp32_exception_decoder ; 	Macht Crash-Adressen lesbarer

lib_deps =
    bodmer/TFT_eSPI
    mikalhart/TinyGPSPlus
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor @ ^1.1.15

board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I src/display
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=47
    -D TFT_MOSI=38
    -D TFT_SCLK=48
    -D TFT_CS=21
    -D TFT_DC=18
    -D TFT_RST=17
    -D TOUCH_CS=10
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_GFXFF=1
    -D SPI_FREQUENCY=20000000
    -D SPI_READ_FREQUENCY=20000000
    -D ESP32_S3 ; damit er weiß das es sich um einen Esp32 handelt 
    -DUSE_HSPI_PORT

